# Generated by Django 5.2.5 on 2025-08-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topics',
            field=models.CharField(blank=True, choices=[('travel', 'TRAVEL'), ('business', 'BUSINESS')], max_length=20, null=True),
        ),
    ]
