# Generated by Django 5.2.5 on 2025-08-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='topics',
        ),
    ]
