# Generated by Django 5.2.5 on 2025-08-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_conversation_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topics',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('business', 'Business')], max_length=20, null=True),
        ),
    ]
