# Generated by Django 5.2.5 on 2025-09-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='topics',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('business', 'Business'), ('academic', 'Academic'), ('conversational', 'Conversational')], max_length=20, null=True),
        ),
    ]
